import random
import string
from dataclasses import dataclass, field

def generate_id() -> str:
    return "".join(random.choices(string.ascii_lowercase, k = 15))

@dataclass
class Student:
    """
    Represents information about students including name,
    surname, active status, login, and an ID.

    Attributes:
    - `name` (str): first name of the student.
    - `surname` (str): last name of the student.
    - `active` (bool): indicates whether the student is active or not (defaulting to `True`).
    - `login` (str): student's login, generated automatically.
    - `id` (str): id of the student, generated by the `generate_id()` function.

    Methods:
    - `__post_init__(self)`: constructor method that generates a login based on name + surname.
    """
    name: str 
    surname: str
    active: bool = field(default=True)
    login: str = field(init=False)
    id: str = field(default_factory=generate_id, init=False)

    def __post_init__(self):
        self.login = (self.name[0] + self.surname).lower()